# NumPy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip list

Package                       Version
----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
bea

In [3]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\DEGREE\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.14.0               |   py39haa95532_0         937 KB
    ------------------------------------------------------------
                                           Total:         937 KB

The following packages will be UPDATED:

  conda                               4.12.0-py39haa95532_0 --> 4.14.0-py39haa95532_0




conda-4.14.0         | 937 KB    |            |   0% 
conda-4.14.0         | 937 KB    | 1          |   2% 
conda-4.14.0         | 937 KB    | #5         |  15% 
conda-4.14.0         | 937 KB    | ##3        |  24% 
conda-4.14.0         | 937 KB    | ####9      |  50% 
conda-4.14.0         | 937 KB    | ######3    |  63% 
conda-4.14.0         | 937 KB    | #######6   |  77% 


'MySQL' is not recognized as an internal or external command,
operable program or batch file.
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
'MySQL' is not recognized as an internal or external command,
operable program or batch file.


In [5]:
import numpy as np

In [6]:
print(np.__version__)

1.21.5


In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
print(np.amin(arr))

1


In [10]:
print(np.percentile(arr,10))

1.9


In [12]:
arr = np.array([[1,2,3],[4,5,6],[1,2,3]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

# Calculate BMI of cricket players

In [2]:
#Heights of players
import numpy as np
hg_in = [61,65,64,69,70,68,64,63,62,66,72]

#convert into numpy array

ht_np = np.array(hg_in)

#convert height from inch to meter by exposing it to 0.0245
ht_np = ht_np * 0.0245

ht_np

array([1.4945, 1.5925, 1.568 , 1.6905, 1.715 , 1.666 , 1.568 , 1.5435,
       1.519 , 1.617 , 1.764 ])

In [3]:
#weight of players in pound

wt_pd = [100,200,160,180,140,155,165,172,180,200,168]

#convert into array
wt_np = np.array(wt_pd)

#convert weight from pound to kg by exposing it to 0.45
wt_np = wt_np *0.45

wt_np



array([45.  , 90.  , 72.  , 81.  , 63.  , 69.75, 74.25, 77.4 , 81.  ,
       90.  , 75.6 ])

In [4]:
#BMI calculation

BMI = wt_np/(ht_np ** 2)
BMI

array([20.1474773 , 35.48817184, 29.28467305, 28.3435777 , 21.41964658,
       25.13010006, 30.19981909, 32.48835283, 35.10503991, 34.42091966,
       24.29543246])

In [5]:
BMI[-1]

24.295432458697764

In [6]:
players = np.array([wt_np,ht_np])
players

array([[45.    , 90.    , 72.    , 81.    , 63.    , 69.75  , 74.25  ,
        77.4   , 81.    , 90.    , 75.6   ],
       [ 1.4945,  1.5925,  1.568 ,  1.6905,  1.715 ,  1.666 ,  1.568 ,
         1.5435,  1.519 ,  1.617 ,  1.764 ]])

In [7]:
players[0][2]

72.0

In [9]:
players[1][2]

1.568

In [10]:
players[1]

array([1.4945, 1.5925, 1.568 , 1.6905, 1.715 , 1.666 , 1.568 , 1.5435,
       1.519 , 1.617 , 1.764 ])

In [12]:
#Teanspose 

pT = players.transpose()
pT

array([[45.    ,  1.4945],
       [90.    ,  1.5925],
       [72.    ,  1.568 ],
       [81.    ,  1.6905],
       [63.    ,  1.715 ],
       [69.75  ,  1.666 ],
       [74.25  ,  1.568 ],
       [77.4   ,  1.5435],
       [81.    ,  1.519 ],
       [90.    ,  1.617 ],
       [75.6   ,  1.764 ]])

In [13]:
pT.shape

(11, 2)

In [18]:
#stastical and mathematical function on players data

print(np.mean(wt_np))

print(np.median(wt_np))

print(np.sum(wt_np))

#standard deviation
print(np.std(wt_np))

#correlation cofficient
print(np.corrcoef(wt_np,ht_np))

74.45454545454545
75.60000000000001
819.0
12.082941667443528
[[1.         0.16451886]
 [0.16451886 1.        ]]
